### PR TITLE
Remove ".class" from file names

### PR DESCRIPTION
**Pull request by bartboy011**
This PR changes the file names of all the classes to remove `.class` from the name. This is no longer needed as we are using autoloading for all files.

Dependent on #88

### CODE REVIEW

**Review by cristiangrama — CHANGES_REQUESTED** [review]
Looks good but we need to address some things in #88

**Comment by bartboy011** [comment]
@cristiangrama Also updated!

**Comment by bartboy011** [comment]
@cristiangrama This is also updated, and includes the removal of `classmap` from composer.json

**Comment by cristiangrama** [comment]
@bartboy011 Please also merge changes from `develop` into this branch.

**Comment by bartboy011** [comment]
@cristiangrama Done!

**Review by cristiangrama — APPROVED** [review]

**Pull request merged**
