### PR TITLE
Flow and formatting suggestions

### PR DESCRIPTION
**Pull request by bryanagee**
In looking at the code, I did this locally to make it easier to follow. Having done that, I figured there would be no harm in seeing whether you'd want the same readability changes in your repo. Feel free to give me feedback if this is contrary to your styling rules, etc.

Cheers!

### CODE REVIEW

**Comment by mthommes** [comment]
Looks great - thanks Bryan!

**Comment by bryanagee** [comment]
@mthommes wow--that was quick =).

**Comment by mthommes** [comment]
Haha, yeah I happened to be checking things the very moment you submitted this. Sometimes we are not as quick. :turtle:

**Comment by bryanagee** [comment]
Good deal--I won't set my expectations by this one instance then. Could I ask you a couple of general questions about the code base?

**Comment by mthommes** [comment]
Of course :) You can ask here, or if it's a more lengthy discussion, feel free to connect with me on Skype: matt.thommes

**Comment by bryanagee** [comment]
Thanks! I would consider Skype, but it's been a while and I don't even remember my username; I'm mostly in Hangouts these days (as buggy as they still are).

To the questions:
1. Is this api something that ActiveCampaign is invested in updating/maintaining? If so, are you guys planning to move to PSR-4, and adopt a specific style guide? 
2. What is the ActiveCampaign position on testing... are there tests for this code that are not public facing? If not, are there plans for them?

**Comment by bryanagee** [comment]
If you'd prefer to respond by email, you can reach me at bryanagee at gmail. Thanks for being available and willing to chat--I really appreciate it!

**Comment by bryanagee** [comment]
On a side note, I'll submit another pull with the matching updates to the example.php  file; looks like a twin with the exception of the include statement.

**Comment by mthommes** [comment]
Please see my responses:

1. Yes, we actively maintain and update this and other API wrappers that we've created. We don't have any current plans to switch to PSR-4, but I imagine it wouldn't be terribly difficult or time-consuming to implement.
2. Are you referring to something like PHPUnit testing?

**Comment by bryanagee** [comment]
Yes: phpunit, behat, etc.

**Comment by mthommes** [comment]
We have various internal testing procedures. If there is something along those lines affecting your use of our API, please let us know and we'll try to help out.

**Comment by bryanagee** [comment]
Awesome; thanks for the info.

I was mostly asking about the testing for two reasons: 1) any time that I use a 3rd party library, I like to be able to run the tests locally and to be sure that any environment or code changes are not going to affect its use. 2) I really like to have tests in place before refactoring much, so I would be able to contribute to the code a lot more if there were tests to show that I hadn't broken things with a misplaced paren or a failed attempt on restructuring a control clause.

I would like to be helpful without being a nuisance, so feel free to put the kibosh on any of my lines of questions/contributions if it's not a worthwhile ROI based on your priorities.

Do you have a style guide or any other contributor documentation?

**Comment by ac-pevans** [comment]
We don't, actually, have such a style guide; so far the level of outside contributions hasn't really demanded it. Down the road, for sure, we would definitely like to have something.

And you're not being a nuisance! We always welcome outside interest and contribution.

**Comment by bryanagee** [comment]
> And you're not being a nuisance!

Yet =). Feel free to let me know if/when that changes.

Might I suggest the adoption of [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) as a style guide? Naturally I wouldn't suggest applying anywhere that breaks the existing API without a major version change. Mostly this would normalize formatting.

**Comment by ac-pevans** [comment]
Suggest away! It's not a bad idea -- at this time we haven't made a decision to adopt that or not.

**Comment by bryanagee** [comment]
Wilco =) I've never been shy about sharing my opinion/suggestions.

**Pull request merged**
