### PR TITLE
Update composer instructions to modern norms

### PR DESCRIPTION
**Pull request by tnorthcutt**

### CODE REVIEW

**Comment by bartboy011** [comment]
@tnorthcutt Take a look at our develop branch. There are a ton of changes we've got in the works, and the final step will be a complete and total overhaul of the README to use modern explanations of composer. The current master branch version of this wrapper is designed to be used both on servers that do and don't support Composer and so the README has been left to reflect that. The new version when released will treat this wrapper as purely a Composer dependency.

**Comment by tnorthcutt** [comment]
@bartboy011 sounds great, thank you. Is the `develop` branch of this repo what the v3 wrapper will be based on, or is that separate entirely?

**Comment by bartboy011** [comment]
The v3 wrapper will be its own entity entirely. We've been using it internally to work out the kinks but a public release should be coming soon!

**Comment by tnorthcutt** [comment]
👏 awesome, great to see active development on this. I'd be happy to help test as soon as you're ready for outside eyes.

**Comment by bartboy011** [comment]
Great, thank you! And yes, this wrapper fell off the roadmap for awhile but we're recommitted to keeping it in good condition. The develop branch can currently be used by requiring the `dev-develop` version from Packagist - https://packagist.org/packages/activecampaign/api-php#dev-develop. Keep in mind that it's still very much a beta and has many breaking changes.

Edit: the develop branch of _this_ repo, not the v3, sorry for any confusion there.

**Pull request closed without merging**
