### PR TITLE
Add Namespacing

### PR DESCRIPTION
**Pull request by bartboy011**
This PR namespaces all classes and updates the README/examples accordingly. 

Additionally, it takes advantage of autoloading and assumes that a user has Composer installed. If the user does not have Composer installed, they can manually import all files.

Finally, it removes an unnecessary config file and examples files to be replaced in a future PR with an expanded README

### CODE REVIEW

**Comment by bartboy011** [comment]
@cristiangrama I believe this is ready now!

**Comment by bartboy011** [comment]
@cristiangrama This has been updated to not include the camel-casing.

**Comment by bartboy011** [comment]
@cristiangrama Ok, should finally be there unless you see something else.

**Review by cristiangrama — APPROVED** [review]
Looks great.

**Pull request merged**
