### PR TITLE
DEVJIRA-8880 :: post data of type array get transformed to double piped strings

### PR DESCRIPTION
**Pull request by w74**
@ActiveCampaign/integration?

### CODE REVIEW

**Comment by w74** [comment]
@mthommes changes made to Connector.

**Comment by w74** [comment]
@mthommes added.

**Comment by w74** [comment]
@ActiveCampaign/deploy

**Comment by w74** [comment]
@ActiveCampaign/deploy

**Comment by w74** [comment]
@ActiveCampaign/deploy

**Comment by kidonchu** [comment]
@ac-pevans Who has permission to merge this repo?

**Comment by ac-pevans** [comment]
@kidonchu you do now.

**Pull request merged**
